title: "Bits and Beer"
description: "Pet Project and Beer Log"
url: "https://amcnevin.github.io"
baseurl: ""

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dark" # air, aqua, contrast, dark, dirt, neon, mint, plum, sunrise

# Search
search: true
search_full_content: true
search_provider: lunr
author:
  name: "Tony McNevin"
  avatar: "/assets/me.jpg"
  bio: ""
  location: "Pittsburgh, PA"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/tony-m-8aa4155"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/amcnevin"

# Site settings
locale: "en-US"
breadcrumbs: false
words_per_minute: 200
atom_feed:
  hide: true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache

# Pagination
paginate: 5
paginate_path: /page:num/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: false
      related: true
      permalink: /:year/:month/:day/:title/
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      prev_next: false
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      prev_next: false

# Include hidden/underscore directories
include:
  - _pages
  - _posts

collections:
  pages:
    output: true
    permalink: /:name/

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - docker-compose.yml
  - .git