# WhatATheme
markdown: kramdown

# URL of the Site
url: 'localhost:4000'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl:

# Title of the Site
title: Tony McNevin
# Description of the Site
description: Eventual Documentation
# URL of Image of the Site
site-image:
# Keywords of the Site
site-keywords:

heroimage: https://media.timeout.com/images/102690880/image.jpg


# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: amcnevin@gmail.com
linkedin_username: tony-m-8aa4155
github_username:  amcnevin

# Google Analytics
google-analytics: /


# Name of the Author
author-name: Tony McNevin
# URL for the Image of the Author
author-image: assets/images/me.jpg
# 60 Words About the Author
author-about: Tinkerer, Dad-joke enjoyer, Software Engineer
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://amcnevin.github.io

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
