# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme


# Site settings
url: 'https://amcnevin.github.io'
baseurl: ''
title: 'Bits and Beer'
description:
permalink: pretty
logo: "/assets/images/bearsuit.png"


# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
  Home: /
  About: /about/
  Blog: /blog/

# Footer nav
#navigation_footer:

social_links:
  LinkedIn: https://www.linkedin.com/in/tony-mcnevin-8aa4155/
  Github: https://github.com/amcnevin
  Link: https://www.hackerrank.com/amcnevin

# Collections
collections:
  posts:
    title:
    output: false
    description: ""
    feature_image: https://picsum.photos/id/190/2048/1365
